//
//  WeatherModel.swift
//  WeatherApp-Project
//
//  Created by Liana Norman on 10/14/19.
//  Copyright © 2019 Liana Norman. All rights reserved.
//

import Foundation

struct WeatherWrapper: Codable {
    let daily: Weather
    let timezone: String
    
}

struct Weather: Codable {
    let icon: String
    let data: [DataWrapper]
    
}

struct DataWrapper: Codable {
    let time: Int
    let summary: String
    let temperatureHigh: Double
    let temperatureLow: Double
    let sunriseTime: Int
    let sunsetTime: Int
    let windSpeed: Double
    let precipType: String
}




//    "daily": {
//        "summary": "No precipitation throughout the week, with high temperatures bottoming out at 61°F on Wednesday.",
//        "icon": "clear-day",
//        "data": [
//            {
//                "time": 1571036400,
//                "summary": "Partly cloudy throughout the day.",
//                "icon": "partly-cloudy-day",
//                "sunriseTime": 1571062700,
//                "sunsetTime": 1571103313,
//                "moonPhase": 0.54,
//                "precipIntensity": 0.0004,
//                "precipIntensityMax": 0.0019,
//                "precipIntensityMaxTime": 1571072400,
//                "precipProbability": 0.07,
//                "precipType": "rain",
//                "temperatureHigh": 65.43,
//                "temperatureHighTime": 1571090400,
//                "temperatureLow": 50.4,
//                "temperatureLowTime": 1571148000,
//                "apparentTemperatureHigh": 64.76,
//                "apparentTemperatureHighTime": 1571090400,
//                "apparentTemperatureLow": 51.05,
//                "apparentTemperatureLowTime": 1571148000,
//                "dewPoint": 45.54,
//                "humidity": 0.65,
//                "pressure": 1014.4,
//                "windSpeed": 4.59,
//                "windGust": 9.08,
//                "windGustTime": 1571097600,
//                "windBearing": 241,
//                "cloudCover": 0.15,
//                "uvIndex": 5,
//                "uvIndexTime": 1571083200,
//                "visibility": 8.995,
//                "ozone": 306.4,
//                "temperatureMin": 52.01,
//                "temperatureMinTime": 1571065200,
//                "temperatureMax": 65.43,
//                "temperatureMaxTime": 1571090400,
//                "apparentTemperatureMin": 52.66,
//                "apparentTemperatureMinTime": 1571065200,
//                "apparentTemperatureMax": 64.76,
//                "apparentTemperatureMaxTime": 1571090400
//            },

//{
//    "latitude": 37.8267,
//    "longitude": -122.4233,
//    "timezone": "America/Los_Angeles",
//    "currently": {
//        "time": 1571073169,
//        "summary": "Partly Cloudy",
//        "icon": "partly-cloudy-day",
//        "precipIntensity": 0,
//        "precipProbability": 0,
//        "temperature": 56.66,
//        "apparentTemperature": 56.66,
//        "dewPoint": 44.53,
//        "humidity": 0.64,
//        "pressure": 1015.48,
//        "windSpeed": 2.59,
//        "windGust": 4.09,
//        "windBearing": 241,
//        "cloudCover": 0.31,
//        "uvIndex": 2,
//        "visibility": 8.802,
//        "ozone": 305.8
//    },
//    "minutely": {
//        "summary": "Partly cloudy for the hour.",
//        "icon": "partly-cloudy-day",
//        "data": [
//            {
//                "time": 1571073120,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073180,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073240,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073300,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073360,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073420,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073480,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073540,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073600,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073660,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073720,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073780,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073840,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073900,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571073960,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074020,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074080,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074140,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074200,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074260,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074320,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074380,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074440,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074500,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074560,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074620,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074680,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074740,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074800,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074860,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074920,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571074980,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075040,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075100,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075160,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075220,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075280,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075340,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075400,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075460,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075520,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075580,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075640,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075700,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075760,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075820,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075880,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571075940,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076000,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076060,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076120,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076180,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076240,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076300,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076360,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076420,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076480,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076540,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076600,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076660,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            },
//            {
//                "time": 1571076720,
//                "precipIntensity": 0,
//                "precipProbability": 0
//            }
//        ]
//    },
//    "hourly": {
//        "summary": "Partly cloudy throughout the day.",
//        "icon": "partly-cloudy-day",
//        "data": [
//            {
//                "time": 1571072400,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 56.24,
//                "apparentTemperature": 56.24,
//                "dewPoint": 44.45,
//                "humidity": 0.65,
//                "pressure": 1015.56,
//                "windSpeed": 2.53,
//                "windGust": 3.99,
//                "windBearing": 237,
//                "cloudCover": 0.31,
//                "uvIndex": 2,
//                "visibility": 8.607,
//                "ozone": 306
//            },
//            {
//                "time": 1571076000,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 58.31,
//                "apparentTemperature": 58.31,
//                "dewPoint": 44.82,
//                "humidity": 0.61,
//                "pressure": 1014.85,
//                "windSpeed": 2.97,
//                "windGust": 4.63,
//                "windBearing": 245,
//                "cloudCover": 0.29,
//                "uvIndex": 3,
//                "visibility": 9.713,
//                "ozone": 305.4
//            },
//            {
//                "time": 1571079600,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 60.69,
//                "apparentTemperature": 60.69,
//                "dewPoint": 47.73,
//                "humidity": 0.62,
//                "pressure": 1015.34,
//                "windSpeed": 4.12,
//                "windGust": 5.07,
//                "windBearing": 231,
//                "cloudCover": 0.19,
//                "uvIndex": 4,
//                "visibility": 10,
//                "ozone": 305
//            },
//            {
//                "time": 1571083200,
//                "summary": "Clear",
//                "icon": "clear-day",
//                "precipIntensity": 0.0018,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 62.91,
//                "apparentTemperature": 62.91,
//                "dewPoint": 49.78,
//                "humidity": 0.62,
//                "pressure": 1015.54,
//                "windSpeed": 5.6,
//                "windGust": 5.88,
//                "windBearing": 236,
//                "cloudCover": 0.12,
//                "uvIndex": 5,
//                "visibility": 10,
//                "ozone": 304.9
//            },
//            {
//                "time": 1571086800,
//                "summary": "Clear",
//                "icon": "clear-day",
//                "precipIntensity": 0.0008,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 64.51,
//                "apparentTemperature": 64.51,
//                "dewPoint": 49.83,
//                "humidity": 0.59,
//                "pressure": 1015.29,
//                "windSpeed": 6.75,
//                "windGust": 7.09,
//                "windBearing": 247,
//                "cloudCover": 0.11,
//                "uvIndex": 4,
//                "visibility": 10,
//                "ozone": 304.6
//            },
//            {
//                "time": 1571090400,
//                "summary": "Clear",
//                "icon": "clear-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 64.76,
//                "apparentTemperature": 64.76,
//                "dewPoint": 49.51,
//                "humidity": 0.58,
//                "pressure": 1014.47,
//                "windSpeed": 7.2,
//                "windGust": 8.06,
//                "windBearing": 251,
//                "cloudCover": 0.1,
//                "uvIndex": 3,
//                "visibility": 10,
//                "ozone": 304
//            },
//            {
//                "time": 1571094000,
//                "summary": "Clear",
//                "icon": "clear-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 63.88,
//                "apparentTemperature": 63.88,
//                "dewPoint": 49.4,
//                "humidity": 0.59,
//                "pressure": 1014.32,
//                "windSpeed": 7.33,
//                "windGust": 8.82,
//                "windBearing": 254,
//                "cloudCover": 0.1,
//                "uvIndex": 2,
//                "visibility": 10,
//                "ozone": 303.3
//            },
//            {
//                "time": 1571097600,
//                "summary": "Clear",
//                "icon": "clear-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 62.23,
//                "apparentTemperature": 62.23,
//                "dewPoint": 49.28,
//                "humidity": 0.63,
//                "pressure": 1014.16,
//                "windSpeed": 7.23,
//                "windGust": 9.08,
//                "windBearing": 250,
//                "cloudCover": 0.1,
//                "uvIndex": 1,
//                "visibility": 10,
//                "ozone": 302.3
//            },
//            {
//                "time": 1571101200,
//                "summary": "Clear",
//                "icon": "clear-day",
//                "precipIntensity": 0.0011,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 60.02,
//                "apparentTemperature": 60.02,
//                "dewPoint": 49.29,
//                "humidity": 0.68,
//                "pressure": 1014.97,
//                "windSpeed": 6.81,
//                "windGust": 8.84,
//                "windBearing": 240,
//                "cloudCover": 0.1,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 300.9
//            },
//            {
//                "time": 1571104800,
//                "summary": "Clear",
//                "icon": "clear-night",
//                "precipIntensity": 0.0016,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 57.25,
//                "apparentTemperature": 57.25,
//                "dewPoint": 49,
//                "humidity": 0.74,
//                "pressure": 1015.19,
//                "windSpeed": 6.19,
//                "windGust": 8.78,
//                "windBearing": 258,
//                "cloudCover": 0.11,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 299.2
//            },
//            {
//                "time": 1571108400,
//                "summary": "Clear",
//                "icon": "clear-night",
//                "precipIntensity": 0.0002,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 56.37,
//                "apparentTemperature": 56.37,
//                "dewPoint": 49.08,
//                "humidity": 0.77,
//                "pressure": 1015.22,
//                "windSpeed": 5.49,
//                "windGust": 7.07,
//                "windBearing": 256,
//                "cloudCover": 0.11,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 297.6
//            },
//            {
//                "time": 1571112000,
//                "summary": "Clear",
//                "icon": "clear-night",
//                "precipIntensity": 0.0002,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 55.84,
//                "apparentTemperature": 55.84,
//                "dewPoint": 49.26,
//                "humidity": 0.79,
//                "pressure": 1015.82,
//                "windSpeed": 5.15,
//                "windGust": 6.45,
//                "windBearing": 249,
//                "cloudCover": 0.12,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 295.9
//            },
//            {
//                "time": 1571115600,
//                "summary": "Clear",
//                "icon": "clear-night",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 55.78,
//                "apparentTemperature": 55.78,
//                "dewPoint": 49.27,
//                "humidity": 0.79,
//                "pressure": 1016.49,
//                "windSpeed": 4.81,
//                "windGust": 5.93,
//                "windBearing": 247,
//                "cloudCover": 0.12,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 294.2
//            },
//            {
//                "time": 1571119200,
//                "summary": "Clear",
//                "icon": "clear-night",
//                "precipIntensity": 0.0011,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 55.92,
//                "apparentTemperature": 55.92,
//                "dewPoint": 49.39,
//                "humidity": 0.79,
//                "pressure": 1017,
//                "windSpeed": 4.48,
//                "windGust": 5.46,
//                "windBearing": 245,
//                "cloudCover": 0.12,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 292.7
//            },
//            {
//                "time": 1571122800,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 56.11,
//                "apparentTemperature": 56.11,
//                "dewPoint": 49.36,
//                "humidity": 0.78,
//                "pressure": 1017.14,
//                "windSpeed": 3.96,
//                "windGust": 4.49,
//                "windBearing": 251,
//                "cloudCover": 0.22,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 291.7
//            },
//            {
//                "time": 1571126400,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0007,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 55.85,
//                "apparentTemperature": 55.85,
//                "dewPoint": 49.48,
//                "humidity": 0.79,
//                "pressure": 1017,
//                "windSpeed": 3.77,
//                "windGust": 4.18,
//                "windBearing": 223,
//                "cloudCover": 0.27,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 291
//            },
//            {
//                "time": 1571130000,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0008,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 55.31,
//                "apparentTemperature": 55.31,
//                "dewPoint": 49.42,
//                "humidity": 0.81,
//                "pressure": 1016.91,
//                "windSpeed": 3.58,
//                "windGust": 3.89,
//                "windBearing": 230,
//                "cloudCover": 0.31,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 290.5
//            },
//            {
//                "time": 1571133600,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0008,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 54.56,
//                "apparentTemperature": 54.56,
//                "dewPoint": 49.36,
//                "humidity": 0.83,
//                "pressure": 1016.96,
//                "windSpeed": 3.27,
//                "windGust": 3.56,
//                "windBearing": 220,
//                "cloudCover": 0.32,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 290
//            },
//            {
//                "time": 1571137200,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0009,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 53.68,
//                "apparentTemperature": 53.68,
//                "dewPoint": 49.32,
//                "humidity": 0.85,
//                "pressure": 1017.06,
//                "windSpeed": 2.96,
//                "windGust": 3.24,
//                "windBearing": 250,
//                "cloudCover": 0.33,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 289.7
//            },
//            {
//                "time": 1571140800,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0009,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 52.71,
//                "apparentTemperature": 52.71,
//                "dewPoint": 49.16,
//                "humidity": 0.88,
//                "pressure": 1017.3,
//                "windSpeed": 2.78,
//                "windGust": 3.07,
//                "windBearing": 239,
//                "cloudCover": 0.35,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 289.2
//            },
//            {
//                "time": 1571144400,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0008,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 51.74,
//                "apparentTemperature": 51.74,
//                "dewPoint": 48.64,
//                "humidity": 0.89,
//                "pressure": 1017.72,
//                "windSpeed": 2.79,
//                "windGust": 3.18,
//                "windBearing": 223,
//                "cloudCover": 0.41,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 288.4
//            },
//            {
//                "time": 1571148000,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0006,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 51.05,
//                "apparentTemperature": 51.05,
//                "dewPoint": 48.07,
//                "humidity": 0.89,
//                "pressure": 1018.26,
//                "windSpeed": 2.93,
//                "windGust": 3.53,
//                "windBearing": 265,
//                "cloudCover": 0.48,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 287.5
//            },
//            {
//                "time": 1571151600,
//                "summary": "Mostly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0.0005,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 51.07,
//                "apparentTemperature": 51.07,
//                "dewPoint": 48.01,
//                "humidity": 0.89,
//                "pressure": 1018.75,
//                "windSpeed": 3.04,
//                "windGust": 3.78,
//                "windBearing": 258,
//                "cloudCover": 0.53,
//                "uvIndex": 0,
//                "visibility": 9.33,
//                "ozone": 286.5
//            },
//            {
//                "time": 1571155200,
//                "summary": "Mostly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0.0003,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 51.78,
//                "apparentTemperature": 51.78,
//                "dewPoint": 48.38,
//                "humidity": 0.88,
//                "pressure": 1019.19,
//                "windSpeed": 3,
//                "windGust": 3.82,
//                "windBearing": 261,
//                "cloudCover": 0.55,
//                "uvIndex": 1,
//                "visibility": 9.671,
//                "ozone": 285.3
//            },
//            {
//                "time": 1571158800,
//                "summary": "Mostly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0.0002,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 52.46,
//                "apparentTemperature": 52.46,
//                "dewPoint": 48.68,
//                "humidity": 0.87,
//                "pressure": 1019.53,
//                "windSpeed": 2.91,
//                "windGust": 3.76,
//                "windBearing": 271,
//                "cloudCover": 0.57,
//                "uvIndex": 2,
//                "visibility": 10,
//                "ozone": 284
//            },
//            {
//                "time": 1571162400,
//                "summary": "Mostly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 54.27,
//                "apparentTemperature": 54.27,
//                "dewPoint": 48.81,
//                "humidity": 0.82,
//                "pressure": 1019.68,
//                "windSpeed": 2.95,
//                "windGust": 3.66,
//                "windBearing": 270,
//                "cloudCover": 0.57,
//                "uvIndex": 3,
//                "visibility": 10,
//                "ozone": 282.5
//            },
//            {
//                "time": 1571166000,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 57.3,
//                "apparentTemperature": 57.3,
//                "dewPoint": 49.2,
//                "humidity": 0.74,
//                "pressure": 1019.3,
//                "windSpeed": 3.14,
//                "windGust": 3.48,
//                "windBearing": 241,
//                "cloudCover": 0.5,
//                "uvIndex": 4,
//                "visibility": 10,
//                "ozone": 280.9
//            },
//            {
//                "time": 1571169600,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 60.21,
//                "apparentTemperature": 60.21,
//                "dewPoint": 49.25,
//                "humidity": 0.67,
//                "pressure": 1018.63,
//                "windSpeed": 3.49,
//                "windGust": 3.49,
//                "windBearing": 291,
//                "cloudCover": 0.39,
//                "uvIndex": 5,
//                "visibility": 10,
//                "ozone": 279
//            },
//            {
//                "time": 1571173200,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 62.86,
//                "apparentTemperature": 62.86,
//                "dewPoint": 49.1,
//                "humidity": 0.61,
//                "pressure": 1018.04,
//                "windSpeed": 3.97,
//                "windGust": 3.97,
//                "windBearing": 267,
//                "cloudCover": 0.3,
//                "uvIndex": 4,
//                "visibility": 10,
//                "ozone": 278.1
//            },
//            {
//                "time": 1571176800,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 65.01,
//                "apparentTemperature": 65.01,
//                "dewPoint": 48.63,
//                "humidity": 0.55,
//                "pressure": 1017.35,
//                "windSpeed": 4.74,
//                "windGust": 4.78,
//                "windBearing": 283,
//                "cloudCover": 0.24,
//                "uvIndex": 3,
//                "visibility": 10,
//                "ozone": 278.5
//            },
//            {
//                "time": 1571180400,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 66.18,
//                "apparentTemperature": 66.18,
//                "dewPoint": 48.19,
//                "humidity": 0.52,
//                "pressure": 1016.65,
//                "windSpeed": 5.62,
//                "windGust": 6.3,
//                "windBearing": 254,
//                "cloudCover": 0.19,
//                "uvIndex": 2,
//                "visibility": 10,
//                "ozone": 279.7
//            },
//            {
//                "time": 1571184000,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 65.84,
//                "apparentTemperature": 65.84,
//                "dewPoint": 48.29,
//                "humidity": 0.53,
//                "pressure": 1016.28,
//                "windSpeed": 6.3,
//                "windGust": 7.68,
//                "windBearing": 266,
//                "cloudCover": 0.16,
//                "uvIndex": 1,
//                "visibility": 10,
//                "ozone": 280.8
//            },
//            {
//                "time": 1571187600,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 63.46,
//                "apparentTemperature": 63.46,
//                "dewPoint": 48.71,
//                "humidity": 0.59,
//                "pressure": 1016.42,
//                "windSpeed": 6.72,
//                "windGust": 8.62,
//                "windBearing": 227,
//                "cloudCover": 0.15,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 281.4
//            },
//            {
//                "time": 1571191200,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 59.71,
//                "apparentTemperature": 59.71,
//                "dewPoint": 49.2,
//                "humidity": 0.68,
//                "pressure": 1017.3,
//                "windSpeed": 6.93,
//                "windGust": 9.28,
//                "windBearing": 307,
//                "cloudCover": 0.15,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 281.8
//            },
//            {
//                "time": 1571194800,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 57.31,
//                "apparentTemperature": 57.31,
//                "dewPoint": 49.43,
//                "humidity": 0.75,
//                "pressure": 1017.68,
//                "windSpeed": 6.78,
//                "windGust": 9.33,
//                "windBearing": 277,
//                "cloudCover": 0.16,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 282.6
//            },
//            {
//                "time": 1571198400,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 56.4,
//                "apparentTemperature": 56.4,
//                "dewPoint": 49.11,
//                "humidity": 0.77,
//                "pressure": 1017.91,
//                "windSpeed": 5.94,
//                "windGust": 8.13,
//                "windBearing": 330,
//                "cloudCover": 0.17,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 284
//            },
//            {
//                "time": 1571202000,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 56.37,
//                "apparentTemperature": 56.37,
//                "dewPoint": 48.89,
//                "humidity": 0.76,
//                "pressure": 1018.13,
//                "windSpeed": 4.72,
//                "windGust": 6.25,
//                "windBearing": 191,
//                "cloudCover": 0.16,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 285.7
//            },
//            {
//                "time": 1571205600,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 56.42,
//                "apparentTemperature": 56.42,
//                "dewPoint": 48.81,
//                "humidity": 0.76,
//                "pressure": 1018.26,
//                "windSpeed": 3.89,
//                "windGust": 5.03,
//                "windBearing": 248,
//                "cloudCover": 0.18,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 286.5
//            },
//            {
//                "time": 1571209200,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 56.23,
//                "apparentTemperature": 56.23,
//                "dewPoint": 49.05,
//                "humidity": 0.77,
//                "pressure": 1018.2,
//                "windSpeed": 3.92,
//                "windGust": 5.32,
//                "windBearing": 246,
//                "cloudCover": 0.23,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 285.8
//            },
//            {
//                "time": 1571212800,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 55.84,
//                "apparentTemperature": 55.84,
//                "dewPoint": 49.22,
//                "humidity": 0.78,
//                "pressure": 1018.01,
//                "windSpeed": 4.36,
//                "windGust": 6.29,
//                "windBearing": 262,
//                "cloudCover": 0.29,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 284.1
//            },
//            {
//                "time": 1571216400,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0,
//                "precipProbability": 0,
//                "temperature": 55.28,
//                "apparentTemperature": 55.28,
//                "dewPoint": 49.31,
//                "humidity": 0.8,
//                "pressure": 1017.76,
//                "windSpeed": 4.62,
//                "windGust": 6.84,
//                "windBearing": 250,
//                "cloudCover": 0.35,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 282.3
//            },
//            {
//                "time": 1571220000,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0005,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 54.71,
//                "apparentTemperature": 54.71,
//                "dewPoint": 49.36,
//                "humidity": 0.82,
//                "pressure": 1017.32,
//                "windSpeed": 4.41,
//                "windGust": 6.32,
//                "windBearing": 244,
//                "cloudCover": 0.39,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 280.5
//            },
//            {
//                "time": 1571223600,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0006,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 54.01,
//                "apparentTemperature": 54.01,
//                "dewPoint": 49.42,
//                "humidity": 0.84,
//                "pressure": 1016.92,
//                "windSpeed": 3.99,
//                "windGust": 5.37,
//                "windBearing": 270,
//                "cloudCover": 0.43,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 278.5
//            },
//            {
//                "time": 1571227200,
//                "summary": "Partly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0006,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 53.34,
//                "apparentTemperature": 53.34,
//                "dewPoint": 49.36,
//                "humidity": 0.86,
//                "pressure": 1016.71,
//                "windSpeed": 3.7,
//                "windGust": 4.8,
//                "windBearing": 262,
//                "cloudCover": 0.48,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 276.9
//            },
//            {
//                "time": 1571230800,
//                "summary": "Mostly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0007,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 52.53,
//                "apparentTemperature": 52.53,
//                "dewPoint": 48.96,
//                "humidity": 0.88,
//                "pressure": 1016.71,
//                "windSpeed": 3.61,
//                "windGust": 4.97,
//                "windBearing": 268,
//                "cloudCover": 0.56,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 275.6
//            },
//            {
//                "time": 1571234400,
//                "summary": "Mostly Cloudy",
//                "icon": "partly-cloudy-night",
//                "precipIntensity": 0.0007,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 51.84,
//                "apparentTemperature": 51.84,
//                "dewPoint": 48.48,
//                "humidity": 0.88,
//                "pressure": 1016.86,
//                "windSpeed": 3.65,
//                "windGust": 5.53,
//                "windBearing": 243,
//                "cloudCover": 0.64,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 274.6
//            },
//            {
//                "time": 1571238000,
//                "summary": "Mostly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0.0007,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 51.94,
//                "apparentTemperature": 51.94,
//                "dewPoint": 48.47,
//                "humidity": 0.88,
//                "pressure": 1017.04,
//                "windSpeed": 3.85,
//                "windGust": 6.12,
//                "windBearing": 255,
//                "cloudCover": 0.72,
//                "uvIndex": 0,
//                "visibility": 10,
//                "ozone": 274.1
//            },
//            {
//                "time": 1571241600,
//                "summary": "Mostly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0.0005,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 53.07,
//                "apparentTemperature": 53.07,
//                "dewPoint": 48.67,
//                "humidity": 0.85,
//                "pressure": 1017.3,
//                "windSpeed": 4.22,
//                "windGust": 6.65,
//                "windBearing": 240,
//                "cloudCover": 0.8,
//                "uvIndex": 1,
//                "visibility": 10,
//                "ozone": 274.3
//            },
//            {
//                "time": 1571245200,
//                "summary": "Mostly Cloudy",
//                "icon": "partly-cloudy-day",
//                "precipIntensity": 0.0004,
//                "precipProbability": 0.01,
//                "precipType": "rain",
//                "temperature": 54.46,
//                "apparentTemperature": 54.46,
//                "dewPoint": 49.25,
//                "humidity": 0.83,
//                "pressure": 1017.65,
//                "windSpeed": 4.74,
//                "windGust": 7.19,
//                "windBearing": 259,
//                "cloudCover": 0.87,
//                "uvIndex": 2,
//                "visibility": 10,
//                "ozone": 275
//            }
//        ]
//    },
//    "daily": {
//        "summary": "No precipitation throughout the week, with high temperatures bottoming out at 61°F on Wednesday.",
//        "icon": "clear-day",
//        "data": [
//            {
//                "time": 1571036400,
//                "summary": "Partly cloudy throughout the day.",
//                "icon": "partly-cloudy-day",
//                "sunriseTime": 1571062700,
//                "sunsetTime": 1571103313,
//                "moonPhase": 0.54,
//                "precipIntensity": 0.0004,
//                "precipIntensityMax": 0.0019,
//                "precipIntensityMaxTime": 1571072400,
//                "precipProbability": 0.07,
//                "precipType": "rain",
//                "temperatureHigh": 65.43,
//                "temperatureHighTime": 1571090400,
//                "temperatureLow": 50.4,
//                "temperatureLowTime": 1571148000,
//                "apparentTemperatureHigh": 64.76,
//                "apparentTemperatureHighTime": 1571090400,
//                "apparentTemperatureLow": 51.05,
//                "apparentTemperatureLowTime": 1571148000,
//                "dewPoint": 45.54,
//                "humidity": 0.65,
//                "pressure": 1014.4,
//                "windSpeed": 4.59,
//                "windGust": 9.08,
//                "windGustTime": 1571097600,
//                "windBearing": 241,
//                "cloudCover": 0.15,
//                "uvIndex": 5,
//                "uvIndexTime": 1571083200,
//                "visibility": 8.995,
//                "ozone": 306.4,
//                "temperatureMin": 52.01,
//                "temperatureMinTime": 1571065200,
//                "temperatureMax": 65.43,
//                "temperatureMaxTime": 1571090400,
//                "apparentTemperatureMin": 52.66,
//                "apparentTemperatureMinTime": 1571065200,
//                "apparentTemperatureMax": 64.76,
//                "apparentTemperatureMaxTime": 1571090400
//            },
//            {
//                "time": 1571122800,
//                "summary": "Partly cloudy throughout the day.",
//                "icon": "partly-cloudy-day",
//                "sunriseTime": 1571149157,
//                "sunsetTime": 1571189628,
//                "moonPhase": 0.57,
//                "precipIntensity": 0.0004,
//                "precipIntensityMax": 0.0009,
//                "precipIntensityMaxTime": 1571137200,
//                "precipProbability": 0.09,
//                "precipType": "rain",
//                "temperatureHigh": 66.85,
//                "temperatureHighTime": 1571180400,
//                "temperatureLow": 51.19,
//                "temperatureLowTime": 1571234400,
//                "apparentTemperatureHigh": 66.18,
//                "apparentTemperatureHighTime": 1571180400,
//                "apparentTemperatureLow": 51.84,
//                "apparentTemperatureLowTime": 1571234400,
//                "dewPoint": 48.9,
//                "humidity": 0.75,
//                "pressure": 1017.83,
//                "windSpeed": 4.16,
//                "windGust": 9.33,
//                "windGustTime": 1571194800,
//                "windBearing": 257,
//                "cloudCover": 0.32,
//                "uvIndex": 5,
//                "uvIndexTime": 1571169600,
//                "visibility": 9.96,
//                "ozone": 284.9,
//                "temperatureMin": 50.4,
//                "temperatureMinTime": 1571148000,
//                "temperatureMax": 66.85,
//                "temperatureMaxTime": 1571180400,
//                "apparentTemperatureMin": 51.05,
//                "apparentTemperatureMinTime": 1571148000,
//                "apparentTemperatureMax": 66.18,
//                "apparentTemperatureMaxTime": 1571180400
//            },
//            {
//                "time": 1571209200,
//                "summary": "Mostly cloudy throughout the day.",
//                "icon": "cloudy",
//                "sunriseTime": 1571235614,
//                "sunsetTime": 1571275945,
//                "moonPhase": 0.6,
//                "precipIntensity": 0.001,
//                "precipIntensityMax": 0.0073,
//                "precipIntensityMaxTime": 1571292000,
//                "precipProbability": 0.15,
//                "precipType": "rain",
//                "temperatureHigh": 61.61,
//                "temperatureHighTime": 1571259600,
//                "temperatureLow": 54.22,
//                "temperatureLowTime": 1571324400,
//                "apparentTemperatureHigh": 60.94,
//                "apparentTemperatureHighTime": 1571259600,
//                "apparentTemperatureLow": 54.87,
//                "apparentTemperatureLowTime": 1571324400,
//                "dewPoint": 50.01,
//                "humidity": 0.79,
//                "pressure": 1015.87,
//                "windSpeed": 5.91,
//                "windGust": 13.37,
//                "windGustTime": 1571274000,
//                "windBearing": 255,
//                "cloudCover": 0.78,
//                "uvIndex": 4,
//                "uvIndexTime": 1571256000,
//                "visibility": 10,
//                "ozone": 276.6,
//                "temperatureMin": 51.19,
//                "temperatureMinTime": 1571234400,
//                "temperatureMax": 61.61,
//                "temperatureMaxTime": 1571259600,
//                "apparentTemperatureMin": 51.84,
//                "apparentTemperatureMinTime": 1571234400,
//                "apparentTemperatureMax": 60.94,
//                "apparentTemperatureMaxTime": 1571259600
//            },
//            {
//                "time": 1571295600,
//                "summary": "Partly cloudy throughout the day.",
//                "icon": "partly-cloudy-day",
//                "sunriseTime": 1571322072,
//                "sunsetTime": 1571362263,
//                "moonPhase": 0.64,
//                "precipIntensity": 0.0005,
//                "precipIntensityMax": 0.0046,
//                "precipIntensityMaxTime": 1571295600,
//                "precipProbability": 0.18,
//                "precipType": "rain",
//                "temperatureHigh": 64.24,
//                "temperatureHighTime": 1571349600,
//                "temperatureLow": 52.46,
//                "temperatureLowTime": 1571407200,
//                "apparentTemperatureHigh": 63.57,
//                "apparentTemperatureHighTime": 1571349600,
//                "apparentTemperatureLow": 53.11,
//                "apparentTemperatureLowTime": 1571407200,
//                "dewPoint": 47.73,
//                "humidity": 0.66,
//                "pressure": 1014.73,
//                "windSpeed": 9.84,
//                "windGust": 26.54,
//                "windGustTime": 1571360400,
//                "windBearing": 296,
//                "cloudCover": 0.38,
//                "uvIndex": 5,
//                "uvIndexTime": 1571342400,
//                "visibility": 10,
//                "ozone": 274.2,
//                "temperatureMin": 54.22,
//                "temperatureMinTime": 1571324400,
//                "temperatureMax": 64.24,
//                "temperatureMaxTime": 1571349600,
//                "apparentTemperatureMin": 54.87,
//                "apparentTemperatureMinTime": 1571324400,
//                "apparentTemperatureMax": 63.57,
//                "apparentTemperatureMaxTime": 1571349600
//            },
//            {
//                "time": 1571382000,
//                "summary": "Partly cloudy throughout the day.",
//                "icon": "clear-day",
//                "sunriseTime": 1571408530,
//                "sunsetTime": 1571448581,
//                "moonPhase": 0.67,
//                "precipIntensity": 0.0001,
//                "precipIntensityMax": 0.0004,
//                "precipIntensityMaxTime": 1571418000,
//                "precipProbability": 0.04,
//                "precipType": "rain",
//                "temperatureHigh": 65.71,
//                "temperatureHighTime": 1571436000,
//                "temperatureLow": 55.57,
//                "temperatureLowTime": 1571497200,
//                "apparentTemperatureHigh": 65.04,
//                "apparentTemperatureHighTime": 1571436000,
//                "apparentTemperatureLow": 56.22,
//                "apparentTemperatureLowTime": 1571497200,
//                "dewPoint": 45.74,
//                "humidity": 0.61,
//                "pressure": 1015.77,
//                "windSpeed": 7.5,
//                "windGust": 22.4,
//                "windGustTime": 1571436000,
//                "windBearing": 290,
//                "cloudCover": 0.06,
//                "uvIndex": 5,
//                "uvIndexTime": 1571428800,
//                "visibility": 10,
//                "ozone": 273.9,
//                "temperatureMin": 52.46,
//                "temperatureMinTime": 1571407200,
//                "temperatureMax": 65.71,
//                "temperatureMaxTime": 1571436000,
//                "apparentTemperatureMin": 53.11,
//                "apparentTemperatureMinTime": 1571407200,
//                "apparentTemperatureMax": 65.04,
//                "apparentTemperatureMaxTime": 1571436000
//            },
//            {
//                "time": 1571468400,
//                "summary": "Partly cloudy throughout the day.",
//                "icon": "partly-cloudy-day",
//                "sunriseTime": 1571494989,
//                "sunsetTime": 1571534900,
//                "moonPhase": 0.7,
//                "precipIntensity": 0.0012,
//                "precipIntensityMax": 0.0085,
//                "precipIntensityMaxTime": 1571497200,
//                "precipProbability": 0.11,
//                "precipType": "rain",
//                "temperatureHigh": 64.14,
//                "temperatureHighTime": 1571522400,
//                "temperatureLow": 55.5,
//                "temperatureLowTime": 1571583600,
//                "apparentTemperatureHigh": 63.47,
//                "apparentTemperatureHighTime": 1571522400,
//                "apparentTemperatureLow": 56.15,
//                "apparentTemperatureLowTime": 1571583600,
//                "dewPoint": 43.9,
//                "humidity": 0.57,
//                "pressure": 1017.11,
//                "windSpeed": 9.72,
//                "windGust": 19.57,
//                "windGustTime": 1571529600,
//                "windBearing": 299,
//                "cloudCover": 0.09,
//                "uvIndex": 5,
//                "uvIndexTime": 1571515200,
//                "visibility": 10,
//                "ozone": 281.7,
//                "temperatureMin": 55.57,
//                "temperatureMinTime": 1571497200,
//                "temperatureMax": 64.14,
//                "temperatureMaxTime": 1571522400,
//                "apparentTemperatureMin": 56.22,
//                "apparentTemperatureMinTime": 1571497200,
//                "apparentTemperatureMax": 63.47,
//                "apparentTemperatureMaxTime": 1571522400
//            },
//            {
//                "time": 1571554800,
//                "summary": "Clear throughout the day.",
//                "icon": "clear-day",
//                "sunriseTime": 1571581448,
//                "sunsetTime": 1571621221,
//                "moonPhase": 0.74,
//                "precipIntensity": 0,
//                "precipIntensityMax": 0,
//                "precipIntensityMaxTime": 1571616000,
//                "precipProbability": 0,
//                "temperatureHigh": 68.94,
//                "temperatureHighTime": 1571612400,
//                "temperatureLow": 61.3,
//                "temperatureLowTime": 1571666400,
//                "apparentTemperatureHigh": 68.27,
//                "apparentTemperatureHighTime": 1571612400,
//                "apparentTemperatureLow": 61.95,
//                "apparentTemperatureLowTime": 1571666400,
//                "dewPoint": 40.12,
//                "humidity": 0.45,
//                "pressure": 1017.99,
//                "windSpeed": 8.44,
//                "windGust": 12.78,
//                "windGustTime": 1571554800,
//                "windBearing": 325,
//                "cloudCover": 0,
//                "uvIndex": 5,
//                "uvIndexTime": 1571601600,
//                "visibility": 10,
//                "ozone": 268,
//                "temperatureMin": 55.5,
//                "temperatureMinTime": 1571583600,
//                "temperatureMax": 68.94,
//                "temperatureMaxTime": 1571612400,
//                "apparentTemperatureMin": 56.15,
//                "apparentTemperatureMinTime": 1571583600,
//                "apparentTemperatureMax": 68.27,
//                "apparentTemperatureMaxTime": 1571612400
//            },
//            {
//                "time": 1571641200,
//                "summary": "Clear throughout the day.",
//                "icon": "clear-day",
//                "sunriseTime": 1571667908,
//                "sunsetTime": 1571707542,
//                "moonPhase": 0.77,
//                "precipIntensity": 0,
//                "precipIntensityMax": 0,
//                "precipIntensityMaxTime": 1571713200,
//                "precipProbability": 0,
//                "temperatureHigh": 73.7,
//                "temperatureHighTime": 1571695200,
//                "temperatureLow": 56.08,
//                "temperatureLowTime": 1571752800,
//                "apparentTemperatureHigh": 73.03,
//                "apparentTemperatureHighTime": 1571695200,
//                "apparentTemperatureLow": 56.73,
//                "apparentTemperatureLowTime": 1571752800,
//                "dewPoint": 28.59,
//                "humidity": 0.25,
//                "pressure": 1020.04,
//                "windSpeed": 5.36,
//                "windGust": 13.04,
//                "windGustTime": 1571680800,
//                "windBearing": 21,
//                "cloudCover": 0,
//                "uvIndex": 5,
//                "uvIndexTime": 1571688000,
//                "visibility": 10,
//                "ozone": 265.5,
//                "temperatureMin": 61.3,
//                "temperatureMinTime": 1571666400,
//                "temperatureMax": 73.7,
//                "temperatureMaxTime": 1571695200,
//                "apparentTemperatureMin": 61.95,
//                "apparentTemperatureMinTime": 1571666400,
//                "apparentTemperatureMax": 73.03,
//                "apparentTemperatureMaxTime": 1571695200
//            }
//        ]
//    },
//    "flags": {
//        "sources": [
//            "nwspa",
//            "cmc",
//            "gfs",
//            "hrrr",
//            "icon",
//            "isd",
//            "madis",
//            "nam",
//            "sref",
//            "darksky"
//        ],
//        "nearest-station": 2.24,
//        "units": "us"
//    },
//    "offset": -7
//}
